<?php

/**
 * This file is part of DSJAS
 * Written and maintained by the DSJAS project.
 *
 * Copyright (C) 2020 - Ethan Marshall
 *
 * DSJAS is free software which is licensed and distributed under
 * the terms of the MIT software licence.
 * Exact terms can be found in the LICENCE file.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * above mentioned licence for specific details.
 */

require "../AdminBootstrap.php";

require ABSPATH . INC . "Users.php";
require ABSPATH . INC . "Banking.php";
require ABSPATH . INC . "csrf.php";


if (isset($_POST["createAccount"])) {
    $csrf = getCSRFSubmission();
    if (!verifyCSRFToken($csrf)) {
        die(getCSRFFailedError());
    }

    if (!isset($_POST["accountName"]) || !isset($_POST["accountType"]) || !isset($_POST["user"])) {
        header("Location: /admin/bank/accounts.php?creationFailed");
        die();
    }

    if (!isset($_POST["initialBalance"]) || $_POST["initialBalance"] == "") {
        $initialBalance = getRandomBalance();
    } else {
        $initialBalance = $_POST["initialBalance"];
    }

    if (!isset($_POST["holderName"]) || $_POST["holderName"] == "") {
        $possibleName = getInfoFromUserID($_POST["user"], "real_name");

        $holderName = ($possibleName == "") ? "" : $possibleName;
    } else {
        $holderName = $_POST["holderName"];
    }

    $disableAccount = isset($_POST["disableAccount"]);

    createAccount($_POST["accountName"], $_POST["user"], $_POST["accountType"], $holderName, $disableAccount, $initialBalance);

    header("Location: /admin/bank/accounts.php?accountCreated");
    die();
}



regenerateCSRF();

?>

<html>
<?php require ABSPATH . INC . "components/AdminSidebar.php"; ?>

<form class="container-fluid" id="content" action="/admin/bank/createAccount.php" method="POST">

    <input type="text" style="visibility: hidden; position: absolute" name="createAccount" value="1">
    <?php getCSRFFormElement(); ?>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="admin-header col col-offset-6">Account creation wizard</h1>
    </div>

    <div class="alert alert-info">
        <strong>Fear not! There's no missing info, ever</strong> Any missing fields will be randomly generated by DSJAS, either with the data already provided or random information.
    </div>

    <div class="card admin-panel">
        <div class="card-header">
            <h3>Basic information</h3>
        </div>

        <div class="card-body">
            <p><strong>Please enter the required information in order to create the account</strong></p>

            <div class="form-group">
                <label for="accountName">Account name</label>
                <input type="text" id="accountName" name="accountName" class="form-control" placeholder="Free Basic Account" required>
                <small id="mutedHelpText" class="form-text text-muted">This will be displayed on the dashboard and can be anything memorable. The name should be something such as "Checking account" or "Free Basic"</small>
            </div>

            <div class="form-group">
                <label for="accountType">Account type</label>
                <select name="accountType" id="accountType" class="form-control" required>
                    <option value="Current">Current account</option>
                    <option value="Savings">Savings account</option>
                    <option value="Shared">Shared account</option>
                    <option value="Misc">Miscellaneous</option>
                </select>
                <small id="mutedHelpText" class="form-text text-muted">If you're not sure, go with <strong>misc</strong> This is purely cosmetic and has no impact on transactions or feature sets</small>
            </div>

            <div class="form-group">
                <label for="userID">Associated user</label>
                <select name="user" id="userID" class="form-control" required>
                    <?php
                    foreach (getAllUsers() as $user) { ?>
                        <option value="<?php echo ($user["user_id"]) ?>" <?php if (isset($_GET["user"]) && $user["user_id"] === $_GET["user"]) {
                                                                                echo ("selected=\"selected\"");
} ?>><?php echo ($user["username"]); ?></option>
                    <?php }
                    ?>
                </select>
                <small id="mutedHelpText" class="form-text text-muted">This user will be considered to own the account. The account will show up on this user's online dashboard and in the manage accounts menu. Accounts can be migrated across users at any time <a href="/admin/bank/migrateAccount.php">Migrate an account</a></small>
            </div>
        </div>
    </div>

    <div class="card admin-panel">
        <div class="card-header">
            <h3>Extra information</h3>
        </div>

        <div class="card-body">
            <div class="form-group">
                <label for="initBalance">Initial balance</label>
                <input type="number" id="initBalance" name="initialBalance" class="form-control" placeholder="$50.00" step="0.01">
                <small id="mutedHelpText" class="form-text text-muted">This can be changed at any time, and can be from any negative or positive decimal. If not set, a random value from -200 to 2,000 will be generated</small>
            </div>

            <div class="form-group">
                <label for="accountName">Holder name</label>
                <input type="text" id="accountName" name="holderName" class="form-control" placeholder="<?php if (isset($_GET["user"])) {
                                                                                                            echo (getInfoFromUserID($_GET["user"], "real_name"));
} else { ?> Holder name <?php
                                                                                                        } ?>">
                <small id="mutedHelpText" class="form-text text-muted">If not set, the associated account's <strong>Real Name</strong> property will be used</small>
            </div>
        </div>
    </div>

    <div class="card admin-panel">
        <div class="card-header">
            <h3>Security information</h3>
        </div>

        <div class="card-body">
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="disableAccount" name="disableAccount">
                <label class="form-check-label" for="disableAccount">Disable this account</label>
                <small id="mutedHelpText" class="form-text text-muted">Disabling an account will prevent transactions from being made. Some themes may show info (like fraud alerts or notifications) for disabled accounts</small>
            </div>
        </div>
    </div>

    <div class="card admin-panel">
        <input type="submit" class="btn btn-primary form-control" value="Create">
    </div>
</form>

</html>